# 使用阿里云预装CUDA 12.4和PyTorch的基础镜像
FROM egs-registry.cn-hangzhou.cr.aliyuncs.com/egs/sd-webui:4.3.9-full-pytorch2.1.2-ubuntu22.04


LABEL maintainer="renyun"
RUN mkdir -p /workspace/stable-diffusion-webui-forge
WORKDIR /workspace/stable-diffusion-webui-forge
RUN git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git && cd stable-diffusion-webui-forge && \
    pip install -r requirements_versions.txt

# 设置APT镜像源（阿里云源）
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends git ffmpeg libgl1 aria2 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
RUN /workspace/miniconda/bin/pip install PyExecJS boto3 aliyun-python-sdk-core aliyun-python-sdk-alimt cryptography
COPY ../webui/download_extension.sh /workspace/stable-diffusion-webui/
RUN chmod +x /workspace/stable-diffusion-webui/download_extension.sh && \
    /workspace/stable-diffusion-webui/download_extension.sh
CMD ["python", "-u", "webui.py", "--listen", "--port", "7680"]

#CMD ["python", "-u", "./launch.py", "--ckpt-dir", "./ckpts", "--listen", "--port", "7680", "--enable-insecure-extension-access", \
#"--disable-safe-unpickle", "--api", "--xformers", "--skip-install"]
