Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: SD原生版本
        SupportOperations:
          - Start
          - Stop
          - Restart
      - TemplateName: SD-Forge版本
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
    ModifyParametersConfig:
      - TemplateName: SD原生版本
        Operation:
          - Name: 变更ECS实例规格
            Description: 变更ECS实例规格
            Type: Custom
            Parameters:
              - EcsInstanceType
          - Name: 变更ECS实例密码
            Description: 变更ECS实例密码
            Type: Custom
            Parameters:
              - InstancePassword
      - TemplateName: SD-Forge版本
        Operation:
          - Name: 变更ECS实例规格
            Description: 变更ECS实例规格
            Type: Custom
            Parameters:
              - EcsInstanceType
          - Name: 变更ECS实例密码
            Description: 变更ECS实例密码
            Type: Custom
            Parameters:
              - InstancePassword
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
        - Name: SD原生版本
          Url: 'ros_templates/template.yaml'
          ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
          AllowedRegions:
            - ap-southeast-1
        - Name: SD-Forge版本
          Url: 'ros_templates/template-forge.yaml'
          ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
          AllowedRegions:
            - ap-southeast-1
      ArtifactRelation:
        ecs_image-stable-diffusion-webui:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
        ecs_image-stable-diffusion-webui-forge:
          ArtifactId: ${Artifact.EcsImageForge.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
      - Name: SD原生版本
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
          - ap-southeast-1
      - Name: SD-Forge版本
        Url: 'ros_templates/template-forge.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
          - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    # 英文版可以再配置Locale为en-US的服务信息
    - Locale: zh-CN
      ShortDescription: demo
      Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image-stable-diffusion-webui
    Description: stable-diffusion ui EcsImage
    SupportRegionIds:
        - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: LYH-RAIN
        RepoName: aliyun-computenest/stable-diffusion-webui
        Branch: main
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      SourceImageId: "m-t4n7hdik5d6zppvw5u9u"
      CommandContent: |-
        mkdir -p /root/application
        if [ -e "/root/code/webui" ]; then cp -r "/root/code/webui" "/root/application/"; fi
        if [ -e "/root/code/.env" ]; then cp -r "/root/code/.env" "/root/application/"; fi
        cd /root/application
        sed -i 's/pull_policy: always/pull_policy: if_not_present/g' webui/docker-compose.yaml
        docker compose -f webui/docker-compose.yaml build 2>&1 | stdbuf -oL grep -viE 'Downloading|sha256|extracting|KiB|Downloaded';
        docker compose -f webui/docker-compose.yaml pull 2>&1 | stdbuf -oL grep -viE 'Downloading|sha256|extracting|KiB|Downloaded' || true;
  EcsImageForge:
    ArtifactType: EcsImage
    ArtifactName: ecs_image-stable-diffusion-webui-forge
    Description: stable-diffusion ui EcsImage forge version
    SupportRegionIds:
      - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: LYH-RAIN
        RepoName: aliyun-computenest/stable-diffusion-webui
        Branch: main
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      SourceImageId: "m-t4ngjsk56pbei5qryne3"
      CommandContent: |-
        mkdir -p /root/application
        if [ -e "/root/code/webui-forge" ]; then cp -r "/root/code/webui-forge" "/root/application/"; fi
        if [ -e "/root/code/.env" ]; then cp -r "/root/code/.env" "/root/application/"; fi
        cd /root/application
        sed -i 's/pull_policy: always/pull_policy: if_not_present/g' webui-forge/docker-compose.yaml
        docker compose -f webui-forge/docker-compose.yaml build 2>&1 | stdbuf -oL grep -viE 'Downloading|sha256|extracting|KiB|Downloaded';
        docker compose -f webui-forge/docker-compose.yaml pull 2>&1 | stdbuf -oL grep -viE 'Downloading|sha256|extracting|KiB|Downloaded' || true;